// Handles that can't be claimed because they collide with app routes or are
// otherwise reserved. Used at create time and by the root /[handle] route.
export const RESERVED_HANDLES = new Set<string>([
  "dashboard",
  "login",
  "signup",
  "logout",
  "api",
  "r",
  "f",
  "l",
  "p",
  "c",
  "d",
  "u",
  "_next",
  "favicon.ico",
  "robots.txt",
  "sitemap.xml",
  "admin",
  "app",
  "help",
  "about",
  "contact",
  "terms",
  "privacy",
  "settings",
  "pricing",
  "blog",
  "docs",
  "support",
  "static",
  "public",
  "assets",
  "traxxr",
]);
